### ISSUE TITLE
Shared keys in secondary section A gets used in templating for secondary section B

### ISSUE THREAD

**Issue by chillbrodev** [uptech/tmptoml#1]
If a key exists in two secondary sections then it can bleed over sometimes. The use case is templating `qa.system2` but it uses the `isShared` property value from `qa.system1` which is incorrect.

The below config can be used to demonstrate the issue.
```toml
[qa]
env=qa
[qa.system1]
isShared = true
[qa.system2]
isShared = false
````
